---
- hosts: all
  # strategy: debug
  gather_facts: yes
  vars_files:
    - vars/all.yml

  roles:
    - setup
    - apache
    - apache_vhost
    - mysql
    - php
    - ioncube
    - adminer
    - nodejs
    - composer
    - grunt
    - sw-cli-tools